### ISSUE TITLE
Lots of unnecessary files installed with the extension?

### ISSUE THREAD

**Issue by henrik-jensen** [theoolee/vscode-reader-mode#3]
First of all thanks for you work - It works, and it's an extension giving the read-only functionality, without needing to alter the core VScode as the earlier and current attempts. 😄  👍 👍 👍  ⭐ ⭐⭐  

But,- why include all those `/syntaxes` and `/snippets` in the distribution. Aren't they either already present in vscode or installed on user preference?

Examples:
```
theoolee.reader-mode-0.3.6/res/typescript-basics/syntaxes
theoolee.reader-mode-0.3.6/res/typescript-basics/snippets
```
Basically all files in folder `theoolee.reader-mode-0.3.6/res/*`
and maybe some of those node_modules in `theoolee.reader-mode-0.3.6/node_modules/*`

Seems, admittedly in a shallow view, that it just duplicate already present functionality available in VSCode?

~~PS! From the readme.md--
"Highlight comments in a soft color, this makes it easier to distinguish between comments and code."
Is this the reason for the extra included `/syntaxes`and `/node_modules`?
I feel this should be addressed through a theme extension that users can themself install if they wish this. Don't think it's suitable for an extension provinding read-only functionality. (If you want your review/read-only code "easier to distinguish between comments and code." you probably also want your general code presented the same way)~~ Edit: i stand corrected.

PPS! But don't get me wrong,- I really appreciate your work and ~~in the future I suspect~~ it will be default installed on all my vscode installations (almost) no matter what 😁.

PPPS! Ahaha, your post, [APIs about achieving "Reader Mode" which is available in IntelliJ](https://github.com/microsoft/vscode-discussions/discussions/432), on vscode-discussions clears up some of my questions. It appears to be inherited in the current design of vscode, that you have to duplicate a lot of the functionality, to achieve your goal to duplicate IntelliJ, hence all the extra syntaxes (but what's with the snippets?).

**Comment by mossgowild** [comment]
This's because the current implementation is hijacking the `original file`, and redirecting all the language providers to the `read-only file`. 

For most of the languages, it works as expected. But for some languages that have built-in language support like typescript, HTML, etc., these language servers would provide information for the `read-only file` without project context, which is not detailed and incorrect, and this extension would also provide correct information with project context from the `original file`. Hence there would be one incorrect information and one correct information when users `hover` or `go to definition` in the `read-only file`, that was confusing.

There is no appropriate way to disable the built-in language support, So I make the file extension of the `read-only file` different from the `original file`, and provide grammar file for files that have this file extension, which is 'just duplicate already present functionality available in vscode'.

**Comment by henrik-jensen** [comment]
Arh,- the built-in languages are the problem. Yeah, I could imagine they get "special" treatment by the core, difficult/impossible? to bypass/hijack.
Thanks for the answer and extension. Closing the issue.
